{
 "title": "ASP.NET OTEL (OpenTelemetry) Metrics",
 "description": "Shows ASP.NET metrics from OpenTelemetry",
 "tags": [
  "dotnet",
  "opentelemetry",
  "otel",
  "prometheus",
  "process",
  "runtime",
  "httpclient",
  "aspnetcore"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(target_info, exported_job)"
    }
   },
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(http_server_duration_milliseconds_bucket{}, http_method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Responses Duration 2xx",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket{exported_job=~\"$app\",http_method=~\"$method\", http_status_code=~\"2..\"}[1m])) by (le)\r\n",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Http Error response rates pr. service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_bucket{exported_job=~\"$app\",http_method=~\"$method\", http_status_code=~\"4..|5..\"}[1m])) by (exported_job, http_status_code, exported_instance)",
     "legendFormat": "{{http_status_code}} | {{exported_job}} | {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Responses Duration 4xx",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket{exported_job=~\"$app\", http_method=~\"$method\", http_status_code=~\"4..\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(process_runtime_dotnet_exceptions_count_total{exported_job=~\"$app\"}[1m])",
     "legendFormat": "| {{exported_job}} | {{exported_instance}} "
    }
   ]
  },
  {
   "title": "Responses Duration 5xx",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_bucket{exported_job=~\"$app\",http_method=~\"$method\", http_status_code=~\"5..\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Rates pr minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_duration_milliseconds_count{exported_job=~\"$app\"}[1m])) by (exported_job, http_route)",
     "legendFormat": "{{exported_job}} | {{http_route}}"
    }
   ]
  },
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "ThreadPool Threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_runtime_dotnet_thread_pool_threads_count{exported_job=~\"$app\"}) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "GC heap size changes",
   "type": "timeseries",
   "description": "Bytes allocated to the managed GC heap from startup of app",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(process_runtime_dotnet_gc_allocations_size_bytes_total{exported_job=~\"$app\"}[1m])) by (exported_job, exported_instance)",
     "legendFormat": "{{exported_job}} | {{exported_instance}}"
    }
   ]
  },
  {
   "title": "ThreadPool Threads Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(process_runtime_dotnet_thread_pool_queue_length{exported_job=~\"$app\"}) by (exported_job, exported_instance)",
     "legendFormat": "{{exported_job}} | {{exported_instance}}"
    }
   ]
  },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(process_runtime_dotnet_gc_collections_count_total{exported_job=~\"$app\"}[1m])) by (exported_job, generation)",
     "legendFormat": "| {{exported_job}} | {{generation}}"
    }
   ]
  }
 ]
}