version: "3.9"
services:
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - ./config/data/tempo:/tmp/tempo
    ports:
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grp

  # Collector
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    restart: always
    command:
      [
        "--config=/etc/otel-collector-config.yaml",
      ]
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888" # pprof extension
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
      - "55679:55679" # zpages extension

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    user: root
    command:
      [
        "--config.file=/etc/prometheus/prometheus.yml",
        "--enable-feature=exemplar-storage",
        "--web.enable-remote-write-receiver"
      ]
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./config/data/prometheus:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    volumes:
      - ./config/dashboards:/var/lib/grafana/dashboards
      - ./config/grafana-dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yaml

  loki:
    image: grafana/loki:latest
    volumes:
      - ./config/loki-local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./config/data/log:/var/log
      - ./config/promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml