receivers:
  otlp: # https://opentelemetry.io/docs/specs/otlp/
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://localhost*"
            - "https://localhost*"
exporters:
  prometheus:
    endpoint: otel:8889

  otlp/traces:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:

extensions:
  health_check:
  zpages:
    endpoint: :55679

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
  telemetry:
    logs:
      level: "debug"