scrape_configs:
  - job_name: 'OpenTelemetry Collector'
    scrape_interval: 1s
    static_configs:
      - targets: ['otel:8889']
      - targets: ['otel:8888']
  
  - job_name: Tempo
    static_configs:
    - targets: ['tempo:3200']